### ISSUE TITLE
does not delegate

### ISSUE THREAD

**Issue by Archebald-now** [haqq-network/frontend#17]
tested the testnet network  https://staking-app-git-feat-staking-haqq-network.vercel.app/, signed transactions for Delegae/Undelegate, successfully, but the coins did not go into delegation/undelegation.
*****************************************************************************************************
Delegation
*****************************************************************************************************
Signature Request 

Cosmos Web3
https://staking-app-git-feat-staking-haqq-network.vercel.app
0x9b649a...6bed4969
Сообщение
account_number:
297
chain_id:
haqq_54211-3
fee:
amount:
0:
amount:
5000
denom:
aISLM
gas:
600000
feePayer:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
memo:
msgs:
0:
type:
cosmos-sdk/MsgDelegate
value:
amount:
amount:
11 000 000 000 000 000 000
denom:
aISLM
delegator_address:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
validator_address:
haqqvaloper1ndjf5ws9y2s56dxsjcsef2rfc4476jtf274f7r
sequence:
17
*****************************************************************************************************
Undelegation
*****************************************************************************************************

Cosmos Web3
https://staking-app-git-feat-staking-haqq-network.vercel.app
0x9b649a...6bed4969
Сообщение
account_number:
297
chain_id:
haqq_54211-3
fee:
amount:
0:
amount:
5000
denom:
aISLM
gas:
600000
feePayer:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
memo:
msgs:
0:
type:
cosmos-sdk/MsgUndelegate
value:
amount:
amount:
1 000 000 000 000 000 000
denom:
aISLM
delegator_address:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
validator_address:
haqqvaloper1ndjf5ws9y2s56dxsjcsef2rfc4476jtf274f7r
sequence:
17

**Comment by olegshilov** [comment]
@Archebald-now fresh version deployed. can you retry now?

**Comment by Archebald-now** [comment]
checked, so far no change

вт, 18 окт. 2022 г., 17:25 Oleg Shilov ***@***.***>:

**Comment by olegshilov** [comment]
@Archebald-now can you recheck?

**Comment by Archebald-now** [comment]
signed the transaction checked in the explorer but the coins were not
delegated
..

for one thing I checked the function of removing rewards, everything is
fine there, they immediately removed


Сообщение

Account_number:
297
Chain_id:
haqq_54211-3
Fee:
Amount:
0:
Amount:
5000
Denom:
aISLM
Gas:
600000
FeePayer:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
Memo:
Msgs:
0:
Type:
cosmos-sdk/MsgDelegate
Value:
Amount:
Amount:
11 111 000 000 000 000 000 000
Denom:
aISLM
Delegator_address:
haqq1ndjf5ws9y2s56dxsjcsef2rfc4476jtfxue86z
Validator_address:
haqqvaloper1ndjf5ws9y2s56dxsjcsef2rfc4476jtf274f7r
Sequence:
54

**Comment by olegshilov** [comment]
@Archebald-now can you recheck please?

**Comment by Archebald-now** [comment]
Hello, if test the original site that was - this
https://staking-app-git-feat-staking-haqq-network.vercel.app/validator/haqqvaloper1ndjf5ws9y2s56dxsjcsef2rfc4476jtf274f7r,
also I can't send in steaking coins
I tried to connect to another site -
https://shell.haqq.network/staking/validator/haqqvaloper1ndjf5ws9y2s56dxsjcsef2rfc4476jtf274f7r,
then here I was able to send to shaking.

I hope I was helpful to you.

пт, 28 лип. 2023, 20:16 користувач Oleg Shilov ***@***.***>
пише:

**Comment by Suleim700** [comment]
Nice project ever
