### ISSUE TITLE
"0"  when you click on the field  -  Amount

### ISSUE THREAD

**Issue by Archebald-now** [haqq-network/frontend#19]
a defect when entering a value, in the field where you need to enter numbers, zero remains (it is better when zero is transparent), since you have to delete it, it is not very convenient
when you click on the field where to enter the number of coins, then zero does not disappear
make transparent - for example
![image](https://user-images.githubusercontent.com/60038570/196411429-59994c64-c18d-4617-b7f2-0239c871d454.png)

**Comment by olegshilov** [comment]
fixed
