### ISSUE TITLE
the page is not reset after the action is performed

### ISSUE THREAD

**Issue by Archebald-now** [haqq-network/frontend#20]
After I delegated to the validator and signed the transaction, I noticed that after I clicked delegate again, the number (number of coins) that I indicated on the eve remained in Amount field

resets only if I force F5 to refresh the page
![image](https://user-images.githubusercontent.com/60038570/196413889-49fa9c06-8f70-4763-88e1-7c055d814437.png)

**Comment by olegshilov** [comment]
fixed
