### ISSUE TITLE
0 which does not disappear

### ISSUE THREAD

**Issue by AlexToTheSun** [haqq-network/frontend#21]
## Description
On [Web3 staking UI](https://staking-app-git-feat-staking-haqq-network.vercel.app/) when you click on the delegate, a **Pop-up** occurs, and it has an active Amount area - in which **0** is an active number that **you need to remove before** entering your own.
- This 0 cannot be deleted using the keyboard (Backspace).
![Снимок экрана от 2022-10-18 15-20-58](https://user-images.githubusercontent.com/30211801/196416018-549e0465-621c-4bd3-9939-2b202bb8e927.png)

- Usually in this case, you enter your Amount, and **0** disappears, since this **0** is needed just to indicate that you need to drive your number into this area. But in Web3 staking UI **0** remains and your Amount is assigned to it.
![image](https://user-images.githubusercontent.com/30211801/196416101-426bc760-f6d3-436b-8e85-cd9b32c50eea.png)

- Only if you select 0 or double-click the mouse - you can enter your number.
![image](https://user-images.githubusercontent.com/30211801/196416359-1ee7fd8d-32d1-4bef-baba-1183093cc840.png)
- Even if you enter a number and try to delete everything by backspace - 0 still remains.

## Expected Behavior
a **Pop-up** has an active Amount area - in which **0** is gray and is not an active number. and disappears, when you type your amount to delegate.

## Actual Behavior
Now **0** is an active number that **you need to remove before** entering your amount.

## Steps to Reproduce

1. connect wallet
2. choose a validator
3. press the delegate button
4. click on amount area
5. start typing a number

## Your Environment

- Browser Name and version: Brave, Firefox
- Operating System and version (desktop or mobile): desktop Manjaro, desktop Windows 10

**Comment by olegshilov** [comment]
@AlexToTheSun thank you for such a detailed description, the error has been fixed
