### ISSUE TITLE
Update favicon for explorer.haqq.network

### ISSUE THREAD

**Issue by VorobevSA** [haqq-network/frontend#246]
## Description

Update the logo in Favicon for explorer

<img width="632" alt="Screenshot 2023-07-17 at 12 02 31" src="https://github.com/haqq-network/frontend/assets/79975485/86ed8078-617c-433c-b30d-cbd701f46e8b">

and fix the favicon for Safari
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-585d0c9a02f4be994d20cd32ecf4e913.png?vsn=d">

https://explorer.haqq.network/apple-touch-icon-585d0c9a02f4be994d20cd32ecf4e913.png?vsn=d
- not founded

**Comment by olegshilov** [comment]
closed as unrelated
