### ISSUE TITLE
[Connect Wallet] No warning message if user uses Safari browser

### ISSUE THREAD

**Issue by Poplavskiye** [haqq-network/frontend#79]
**ENV**: prod 

**Steps**: 

1. Open website from Safari browser
2. Click on "Connect Wallet"

**Expected result:** Download "Metamask" suggestion appears in modal window with Link to store
**Actual result:** Nothing happens

**Comment by olegshilov** [comment]
Irrelevant issue. Safari now have ability to use WalletConnect
