### ISSUE TITLE
[Minor Bug] Broken links in the list of modules in HAQQ Network website

### ISSUE THREAD

**Issue by pizofreude** [haqq-network/frontend#810]
## Description

There are several broken links in the list of production-grade modules for the HAQQ Network Docs that need to be addressed as found [here](https://docs.haqq.network/network/modules/).

## Expected Behavior

Correction of the broken links to ensure proper navigation and access to module documentation.

When we click all item in the list of production-grade modules, it should return the page correctly. For example, when we click **bank**, it should return https://docs.haqq.network/network/modules/bank/

## Actual Behavior

All links in the list of production-grade modules are broken. For example: [bank](https://docs.haqq.network/network/modules/modules/bank/)

Here's the full list of the broken links:
[bank](https://docs.haqq.network/network/modules/modules/bank/) - Token transfer functionalities extended to natively support ERC-20 token transfers.
[coinomics](https://docs.haqq.network/network/modules/modules/coinomics/) - ...
[epochs](https://docs.haqq.network/network/modules/modules/epochs/) - Executes custom state transitions every period (aka epoch).
[erc20](https://docs.haqq.network/network/modules/modules/erc20/) - Trustless, on-chain bidirectional internal conversion of tokens between HAQQ EVM and Cosmos runtimes.
[evm](https://docs.haqq.network/network/modules/modules/evm/) - Smart Contract deployment and execution on Cosmos
[feemarket](https://docs.haqq.network/network/modules/modules/feemarket/) - Fee market implementation based on the EIP1559 specification.
[ibc](https://docs.haqq.network/network/modules/modules/ibc/) - Cross-chain token transfer functionalities extended to natively support ERC-20 tokens.
[vesting](https://docs.haqq.network/network/modules/modules/vesting/) - Vesting accounts with lockup and clawback capabilities.
[liquidvesting](https://docs.haqq.network/network/modules/modules/liquidvesting/) - Liquidate and redeem vesting tokens with the preservation of the vesting schedule.

## Possible Fix

Simply replaced the broken links with the correct ones.

## Steps to Reproduce

1. Go to https://docs.haqq.network/network/modules/
2. Click any of the hyperlinks in the list of production-grade modules
3. It will redirect to "Page not found" error 404:
![image](https://github.com/haqq-network/frontend/assets/108355948/22ff419c-db4e-4b48-8381-e6ecbf638479)

**Comment by olegshilov** [comment]
This is the wrong repository for this type of issue. The documentation repository can be found [here](https://github.com/haqq-network/docs). Therefore, I will close this issue because it has already been fixed.
